#!/usr/bin/env bash
# Detect or install CUDA toolkit (nvcc) for vLLM / FlashInfer JIT.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=lib_common.sh
source "${SCRIPT_DIR}/lib_common.sh"
ENV_FILE="${PROJECT_ROOT}/scripts/env.cuda.sh"

find_nvcc() {
  if command -v nvcc &>/dev/null; then
    command -v nvcc
    return 0
  fi
  for candidate in \
    /usr/local/cuda/bin/nvcc \
    /usr/lib/nvidia-cuda-toolkit/bin/nvcc \
    /usr/bin/nvcc; do
    if [[ -x "${candidate}" ]]; then
      echo "${candidate}"
      return 0
    fi
  done
  return 1
}

install_system_packages() {
  if [[ "${INSTALL_CUDA_PACKAGES:-1}" != "1" ]]; then
    echo "Skipping CUDA toolkit install (INSTALL_CUDA_PACKAGES=0)"
    return 1
  fi
  if ! command -v apt-get &>/dev/null; then
    echo "apt-get not available; install CUDA toolkit manually."
    return 1
  fi
  echo "Installing CUDA toolkit and build tools (requires sudo)..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    ninja-build \
    git \
    curl \
    wget \
    python3-venv \
    python3-pip \
    nvidia-cuda-toolkit \
    nvidia-cuda-dev \
    2>/dev/null || sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    ninja-build \
    git \
    curl \
    wget \
    python3-venv \
    python3-pip \
    nvidia-cuda-toolkit
}

write_env_file() {
  local nvcc_path="$1"
  local cuda_home
  cuda_home="$(resolve_cuda_home_from_nvcc "${nvcc_path}")"
  local lib_path="${cuda_home}/lib64"
  if [[ ! -d "${lib_path}" && -d "${cuda_home}/lib/x86_64-linux-gnu" ]]; then
    lib_path="${cuda_home}/lib/x86_64-linux-gnu"
  elif [[ ! -d "${lib_path}" && -d /usr/lib/x86_64-linux-gnu ]]; then
    lib_path="/usr/lib/x86_64-linux-gnu"
  fi
  cat > "${ENV_FILE}" << EOF
# Generated by scripts/setup_cuda_env.sh — sourced automatically via .venv/bin/activate.d/
export CUDA_HOME="${cuda_home}"
export PATH="${cuda_home}/bin:\${PATH}"
export LD_LIBRARY_PATH="${lib_path}:\${LD_LIBRARY_PATH:-}"
# FlashInfer JIT needs nvcc/CUB matching the driver; apt toolkit on H200 often fails (FlagHeads).
export VLLM_USE_FLASHINFER_SAMPLER=0
EOF
  echo "Wrote ${ENV_FILE} (CUDA_HOME=${cuda_home}, VLLM_USE_FLASHINFER_SAMPLER=0)"
}

write_fallback_env() {
  cat > "${ENV_FILE}" << 'EOF'
# CUDA toolkit not found — FlashInfer sampler disabled (slower sampling, still works)
export VLLM_USE_FLASHINFER_SAMPLER=0
EOF
  echo "WARNING: nvcc not found. Wrote fallback ${ENV_FILE}"
}

main() {
  echo "=== CUDA toolkit setup ==="
  NVCC="$(find_nvcc || true)"
  if [[ -z "${NVCC}" ]]; then
    install_system_packages || true
    NVCC="$(find_nvcc || true)"
  fi
  if [[ -n "${NVCC}" ]]; then
    echo "Found nvcc: ${NVCC}"
    nvcc --version | tail -3 || true
    write_env_file "${NVCC}"
    return 0
  fi
  write_fallback_env
  return 1
}

main "$@"
